name: CI

on:
    push:
        branches: ["main"]
    pull_request:

jobs:
    test:
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                rust: [stable, beta, nightly, 1.64.0]
                exclude:
                    - os: macos-latest
                      rust: beta
                    - os: windows-latest
                      rust: beta
                    - os: macos-latest
                      rust: 1.64.0
                    - os: windows-latest
                      rust: 1.64.0
                    - os: macos-latest
                      rust: nightly
                    - os: windows-latest
                      rust: nightly

        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v3
            - uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: ${{ matrix.rust }}
                  override: true
            - uses: Swatinem/rust-cache@v2
            - run: cargo build --all-features --all-targets

    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: stable
                  override: true
                  components: rustfmt, clippy
            - uses: Swatinem/rust-cache@v2
            - run: cargo fmt --all --check
            - run: cargo clippy --workspace --all-targets --all-features -- -D warnings
            - name: Checking doc references
              uses: Icelk/rustdoc-link-check@v2
              with:
                  private: true

    audit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: EmbarkStudios/cargo-deny-action@v1
